# Generated by Django 4.2.5 on 2023-10-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikeshop', '0005_order_shipping_addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='quantity',
            new_name='item_quantity',
        ),
    ]
